name: Kittygram CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  backend_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install ruff

      - name: Run ruff
        run: |
          ruff check backend/

  backend_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run backend tests
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          cd backend
          python manage.py migrate
          python manage.py test

  frontend_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up nodeJS
      # Это готовый воркфлоу для установки Node.js на раннер
      uses: actions/setup-node@v4
      with:
        # Это параметр воркфлоу, указывающий нужную версию Node.js
        node-version: 18
    - name: Install dependencies
      # Эта команда устанавливает зависимости для фронтенда
      run: |
        cd frontend/
        npm ci
    - name: Test frontend
      # Запускаем тесты
      run: |
        cd frontend/
        npm run test
  build_frontend_and_push_to_docker_hub:
    name: Push frontend Docker image to DockerHub
    runs-on: ubuntu-latest
    needs: frontend_tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          push: true
          tags: username/taski_frontend:latest


  build_and_push:
    runs-on: ubuntu-latest
    needs: [backend_lint, backend_tests, frontend_tests]

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kittygram_backend ./backend

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kittygram_frontend ./frontend

      - name: Build nginx image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kittygram_gateway ./nginx

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/kittygram_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/kittygram_frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/kittygram_gateway

  telegram_notify:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Send Telegram message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ Kittygram CI/CD успешно завершён!"